"""emissions targets + carbon credits

Revision ID: 342420eea1c1
Revises: 3e3b75e93430
Create Date: 2026-07-11 10:00:21.062119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '342420eea1c1'
down_revision: Union[str, None] = '3e3b75e93430'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carbon_credits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('registry', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('vintage_year', sa.Integer(), nullable=True),
    sa.Column('quantity_tco2e', sa.Float(), nullable=False),
    sa.Column('credit_type', sa.String(), nullable=False),
    sa.Column('ccp_approved', sa.Boolean(), nullable=True),
    sa.Column('vcmi_claim', sa.String(), nullable=True),
    sa.Column('retired', sa.Boolean(), nullable=True),
    sa.Column('retirement_date', sa.String(), nullable=True),
    sa.Column('applied_to_run_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.CheckConstraint('quantity_tco2e > 0', name='ck_credit_qty_pos'),
    sa.ForeignKeyConstraint(['applied_to_run_id'], ['calculation_runs.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emissions_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=False),
    sa.Column('scope_coverage', sa.String(), nullable=False),
    sa.Column('base_run_id', sa.Integer(), nullable=False),
    sa.Column('base_year', sa.Integer(), nullable=False),
    sa.Column('target_year', sa.Integer(), nullable=False),
    sa.Column('target_reduction_pct', sa.Float(), nullable=False),
    sa.Column('ambition', sa.String(), nullable=True),
    sa.Column('sbti_validated', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.CheckConstraint('target_reduction_pct >= 0 AND target_reduction_pct <= 1', name='ck_target_reduction_frac'),
    sa.CheckConstraint('target_year > base_year', name='ck_target_year_after_base'),
    sa.ForeignKeyConstraint(['base_run_id'], ['calculation_runs.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emissions_targets')
    op.drop_table('carbon_credits')
    # ### end Alembic commands ###
