"""cbam goods + default values

Revision ID: 3e3b75e93430
Revises: 083915258aeb
Create Date: 2026-07-10 15:33:43.066793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e3b75e93430'
down_revision: Union[str, None] = '083915258aeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cbam_default_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cn_code_prefix', sa.String(), nullable=False),
    sa.Column('good_category', sa.String(), nullable=False),
    sa.Column('direct_t_co2e_per_t', sa.Float(), nullable=False),
    sa.Column('indirect_t_co2e_per_t', sa.Float(), nullable=False),
    sa.Column('valid_year', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.String(), nullable=True),
    sa.CheckConstraint('direct_t_co2e_per_t >= 0', name='ck_cbam_direct_nonneg'),
    sa.CheckConstraint('indirect_t_co2e_per_t >= 0', name='ck_cbam_indirect_nonneg'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cbam_goods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('cn_code', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity_tonnes', sa.Float(), nullable=False),
    sa.Column('origin_country', sa.String(), nullable=False),
    sa.Column('import_date', sa.String(), nullable=False),
    sa.Column('installation', sa.Text(), nullable=True),
    sa.Column('actual_direct_t_per_t', sa.Float(), nullable=True),
    sa.Column('actual_indirect_t_per_t', sa.Float(), nullable=True),
    sa.Column('actual_verified', sa.Boolean(), nullable=True),
    sa.Column('carbon_price_paid_eur_per_t', sa.Float(), nullable=True),
    sa.CheckConstraint('quantity_tonnes > 0', name='ck_cbam_qty_pos'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cbam_goods')
    op.drop_table('cbam_default_values')
    # ### end Alembic commands ###
