"""financed positions (pcaf)

Revision ID: 3f4b66c2b246
Revises: 267fdea4926f
Create Date: 2026-07-11 12:22:13.959953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f4b66c2b246'
down_revision: Union[str, None] = '267fdea4926f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financed_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('investee_name', sa.String(), nullable=False),
    sa.Column('asset_class', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('outstanding_amount', sa.Float(), nullable=False),
    sa.Column('attribution_denominator', sa.Float(), nullable=False),
    sa.Column('investee_scope1_tco2e', sa.Float(), nullable=False),
    sa.Column('investee_scope2_tco2e', sa.Float(), nullable=False),
    sa.Column('investee_scope3_tco2e', sa.Float(), nullable=True),
    sa.Column('investee_revenue_millions', sa.Float(), nullable=True),
    sa.Column('data_quality_score', sa.Integer(), nullable=False),
    sa.Column('as_of_date', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.CheckConstraint('attribution_denominator > 0', name='ck_fp_denom_pos'),
    sa.CheckConstraint('data_quality_score >= 1 AND data_quality_score <= 5', name='ck_fp_dq'),
    sa.CheckConstraint('outstanding_amount >= 0', name='ck_fp_outstanding_nonneg'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('financed_positions')
    # ### end Alembic commands ###
