"""taxonomy activities

Revision ID: 59a92aabfff1
Revises: f039492ec8d1
Create Date: 2026-07-12 23:41:18.249320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59a92aabfff1'
down_revision: Union[str, None] = 'f039492ec8d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taxonomy_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('reporting_year', sa.Integer(), nullable=False),
    sa.Column('turnover', sa.Float(), nullable=False),
    sa.Column('capex', sa.Float(), nullable=False),
    sa.Column('opex', sa.Float(), nullable=False),
    sa.Column('eligible', sa.Boolean(), nullable=False),
    sa.Column('substantial_contribution', sa.Boolean(), nullable=False),
    sa.Column('dnsh_pass', sa.Boolean(), nullable=False),
    sa.Column('minimum_safeguards_pass', sa.Boolean(), nullable=False),
    sa.Column('objective', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.CheckConstraint('turnover >= 0 AND capex >= 0 AND opex >= 0', name='ck_taxo_nonneg'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('taxonomy_activities')
    # ### end Alembic commands ###
