"""upload idempotency hash

Revision ID: 5a2311e78fb8
Revises: c490ab48eb23
Create Date: 2026-07-09 22:13:02.816077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a2311e78fb8'
down_revision: Union[str, None] = 'c490ab48eb23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('upload_hash', sa.String(), nullable=True))
    op.create_index(op.f('ix_activities_upload_hash'), 'activities', ['upload_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activities_upload_hash'), table_name='activities')
    op.drop_column('activities', 'upload_hash')
    # ### end Alembic commands ###
