"""per-gas emission factor columns

Revision ID: 755a0f27f91a
Revises: 9c6e4aceb94a
Create Date: 2026-07-09 14:42:38.059386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '755a0f27f91a'
down_revision: Union[str, None] = '9c6e4aceb94a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emission_factors', sa.Column('kg_co2', sa.Float(), nullable=True))
    op.add_column('emission_factors', sa.Column('kg_ch4', sa.Float(), nullable=True))
    op.add_column('emission_factors', sa.Column('kg_n2o', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emission_factors', 'kg_n2o')
    op.drop_column('emission_factors', 'kg_ch4')
    op.drop_column('emission_factors', 'kg_co2')
    # ### end Alembic commands ###
