"""dual scope2: market instruments + market total

Revision ID: 7b0d9cc6222b
Revises: 755a0f27f91a
Create Date: 2026-07-09 15:35:37.662312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b0d9cc6222b'
down_revision: Union[str, None] = '755a0f27f91a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_instruments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('instrument_type', sa.String(), nullable=False),
    sa.Column('kg_co2e_per_kwh', sa.Float(), nullable=False),
    sa.Column('start_date', sa.String(), nullable=True),
    sa.Column('end_date', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('calculation_runs', sa.Column('total_co2e_market', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calculation_runs', 'total_co2e_market')
    op.drop_table('market_instruments')
    # ### end Alembic commands ###
