"""ch4 origin + instrument volume and vintage

Revision ID: 85fd4ab1e9cb
Revises: 7b0d9cc6222b
Create Date: 2026-07-09 21:23:15.300029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85fd4ab1e9cb'
down_revision: Union[str, None] = '7b0d9cc6222b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emission_factors', sa.Column('ch4_origin', sa.String(), nullable=True))
    op.add_column('market_instruments', sa.Column('coverage_kwh', sa.Float(), nullable=True))
    op.add_column('market_instruments', sa.Column('gwp_set', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('market_instruments', 'gwp_set')
    op.drop_column('market_instruments', 'coverage_kwh')
    op.drop_column('emission_factors', 'ch4_origin')
    # ### end Alembic commands ###
