"""spend fx: fx_rates, price_indices, factor base_year/price_basis

Revision ID: 8686dd35c18a
Revises: 8b1f046a5370
Create Date: 2026-07-10 02:57:36.237714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8686dd35c18a'
down_revision: Union[str, None] = '8b1f046a5370'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fx_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_currency', sa.String(), nullable=False),
    sa.Column('quote_currency', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.CheckConstraint('rate > 0', name='ck_fx_rate_pos'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('base_currency', 'quote_currency', 'year', name='uq_fx')
    )
    op.create_table('price_indices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('index_value', sa.Float(), nullable=False),
    sa.CheckConstraint('index_value > 0', name='ck_price_index_pos'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('currency', 'year', name='uq_price_index')
    )
    op.add_column('emission_factors', sa.Column('base_year', sa.Integer(), nullable=True))
    op.add_column('emission_factors', sa.Column('price_basis', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emission_factors', 'price_basis')
    op.drop_column('emission_factors', 'base_year')
    op.drop_table('price_indices')
    op.drop_table('fx_rates')
    # ### end Alembic commands ###
