"""run data_quality_score

Revision ID: 8b1f046a5370
Revises: 910bce36f25d
Create Date: 2026-07-10 02:41:14.004182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b1f046a5370'
down_revision: Union[str, None] = '910bce36f25d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calculation_runs', sa.Column('data_quality_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calculation_runs', 'data_quality_score')
    # ### end Alembic commands ###
