"""lca assessments + items

Revision ID: 8b68b0662e1b
Revises: 3f4b66c2b246
Create Date: 2026-07-11 12:59:04.937912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b68b0662e1b'
down_revision: Union[str, None] = '3f4b66c2b246'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lca_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('standard', sa.String(), nullable=False),
    sa.Column('functional_unit', sa.String(), nullable=False),
    sa.Column('functional_unit_quantity', sa.Float(), nullable=False),
    sa.Column('gwp_set', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.CheckConstraint('functional_unit_quantity > 0', name='ck_lca_fu_pos'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lca_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('factor_id', sa.Integer(), nullable=True),
    sa.Column('allocation_factor', sa.Float(), nullable=False),
    sa.CheckConstraint('allocation_factor >= 0 AND allocation_factor <= 1', name='ck_lca_alloc'),
    sa.ForeignKeyConstraint(['assessment_id'], ['lca_assessments.id'], ),
    sa.ForeignKeyConstraint(['factor_id'], ['emission_factors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lca_items')
    op.drop_table('lca_assessments')
    # ### end Alembic commands ###
