"""lca methods: method_type, boundary, biogenic pool

Revision ID: 910bce36f25d
Revises: 5a2311e78fb8
Create Date: 2026-07-09 22:27:52.987440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '910bce36f25d'
down_revision: Union[str, None] = '5a2311e78fb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calculation_runs', sa.Column('total_biogenic_co2e', sa.Float(), nullable=True))
    op.add_column('emission_factors', sa.Column('method_type', sa.String(), nullable=True))
    op.add_column('emission_factors', sa.Column('lca_boundary', sa.String(), nullable=True))
    op.add_column('emission_factors', sa.Column('kg_co2_biogenic', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emission_factors', 'kg_co2_biogenic')
    op.drop_column('emission_factors', 'lca_boundary')
    op.drop_column('emission_factors', 'method_type')
    op.drop_column('calculation_runs', 'total_biogenic_co2e')
    # ### end Alembic commands ###
