"""assurance engagements + findings

Revision ID: 9a832584ec15
Revises: 12a862a95130
Create Date: 2026-07-11 10:40:29.371253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a832584ec15'
down_revision: Union[str, None] = '12a862a95130'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assurance_engagements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('standard', sa.String(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('assuror_name', sa.String(), nullable=True),
    sa.Column('period_label', sa.String(), nullable=True),
    sa.Column('materiality_pct', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('opinion', sa.String(), nullable=True),
    sa.Column('opinion_note', sa.Text(), nullable=True),
    sa.Column('access_token_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('concluded_at', sa.String(), nullable=True),
    sa.CheckConstraint('materiality_pct > 0 AND materiality_pct <= 100', name='ck_assurance_materiality'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['calculation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assurance_findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engagement_id', sa.Integer(), nullable=False),
    sa.Column('line_item_id', sa.Integer(), nullable=True),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['engagement_id'], ['assurance_engagements.id'], ),
    sa.ForeignKeyConstraint(['line_item_id'], ['emission_line_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assurance_findings')
    op.drop_table('assurance_engagements')
    # ### end Alembic commands ###
