"""api key rotation + revocation

Revision ID: f039492ec8d1
Revises: 8b68b0662e1b
Create Date: 2026-07-12 23:15:56.194481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f039492ec8d1'
down_revision: Union[str, None] = '8b68b0662e1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # NOT NULL added to an existing table needs a server default for prior rows.
    op.add_column('organisations', sa.Column('api_key_revoked', sa.Boolean(),
                                             nullable=False, server_default=sa.false()))
    op.add_column('organisations', sa.Column('key_rotated_at', sa.String(), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organisations', 'key_rotated_at')
    op.drop_column('organisations', 'api_key_revoked')
    # ### end Alembic commands ###
